services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data   # Zookeeper 데이터 볼륨
      - zookeeper_log:/var/lib/zookeeper/log     # Zookeeper 로그 볼륨
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092 # 모든 네트워크 인터페이스(0.0.0.0)에서 포트 9092로 연결 요청을 수신할 수 있도록 설정합니다.
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.178.0.2:9092 # 외부 클라이언트가 Kafka에 어떻게 접근할 수 있는지 길을 제공하는 것 -> 근데 외부 클라이언트가 접근할 이유가 없어서 사실상 이거는 의미가 없다.
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data           # Kafka 데이터 볼륨
    depends_on:
      - zookeeper
    networks:
      - kafka-network

volumes:
  zookeeper_data:
    driver: local
  zookeeper_log:
    driver: local
  kafka_data:
    driver: local

networks:
  kafka-network:
    driver: bridge

